backends/rails/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#main'
  get '/subproject', to: 'static_pages#subproject'
  get '/admin', to: 'static_pages#admin'
  get '/admin/*details', to: 'static_pages#admin'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :api, defaults: {format: 'json'} do
    get '/projects', to: 'projects#index'

    get '/forms', to: 'forms#index', as: :forms
    post '/forms', to: 'forms#create'
    get '/forms/:number/versions', to: 'forms#versions', as: :form_versions
    get '/forms/:number/versions/:version', to: 'forms#version', as: :form_version
    put '/forms/:number/versions/:version', to: 'forms#update', as: :form_update
    post '/forms/:number/versions/:version/publish', to: 'forms#publish', as: :form_publish
    post '/forms/:number/versions/:version/unpublish', to: 'forms#unpublish', as: :form_unpublish
    get '/forms/:number/versions/:version/responses', to: 'forms#responses', as: :form_responses
  end

  get '/forms/:project', to: 'form_responses#project_forms', as: :project_forms
  get '/forms/:project/:slug', to: 'form_responses#new', as: :new_form_response
  post '/forms/:project/:slug', to: 'form_responses#create'
  get '/forms/:project/:slug/done', to: 'form_responses#done', as: :form_response_created

end

backends/rails/app/controllers/form_responses_controller.rb
class FormResponsesController < ApplicationController

  rescue_from ActiveRecord::RecordNotFound, with: :render_404_page
  rescue_from ActiveRecord::RecordInvalid, with: :render_form

  before_action :get_published_form, except: :project_forms

  def new
    FormsService.build_response(@form, {})
    render_form
  end

  def create
    FormsService.create_response(@form, params.permit![:responses], auth.current_user)
    flash[:done] = true
    redirect_to form_response_created_path(@form.project, @form.slug)
  end

  def done
    if flash[:done]
      render layout: project_info[:layout]
    else
      redirect_to project_info[:root]
    end
  end

  def project_forms
    if project_info.nil?
      render_404_page
    else
      @forms = FormsService.published_forms(params[:project])
      render :project_forms, layout: project_info[:layout]
    end
  end

  private

  def get_published_form
    @form = FormsService.published_form(params[:project], params[:slug])
  end

  def project_info
    PROJECTS[params[:project]]
  end

  def render_form
    form_response = @form.responses.proxy_association.target[0]
    @field_responses = field_responses_hash(form_response)
    render :new, layout: project_info[:layout]
  end

  def field_responses_hash(form_response)
    Hash[form_response.field_responses.map { |fr| [fr.form_field.id, fr] }]
  end

end

backends/rails/app/views/form_responses/_address_field.html.erb
<% if field.details[:question] %>
<div class="question"><%= md2html(field.details[:question]) %></div>
<% end %>

<label<% if response.errors.include?(:addressLine1) %> class="error"<% end %>>Address Line 1
  <input type="text" name="responses[<%= field.id %>][addressLine1]" value="<%= response.details[:addressLine1] %>">
</label>
<% if response.errors.include?(:addressLine1) %>
  <small class="error addressLine1">
    <ul>
    <% response.errors.full_messages_for(:addressLine1).each do |msg| %>
      <li><%= msg.sub('line', ' Line ') %></li>
    <% end %>
    </ul>
  </small>
<% end %>

<label<% if response.errors.include?(:addressLine2) %> class="error"<% end %>>Address Line 2
  <input type="text" name="responses[<%= field.id %>][addressLine2]" value="<%= response.details[:addressLine2] %>">
</label>
<% if response.errors.include?(:addressLine2) %>
  <small class="error addressLine2">
    <ul>
    <% response.errors.full_messages_for(:addressLine2).each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </small>
<% end %>

<div class="row city-state-zip">
  <div class="small-6 columns">
    <label<% if response.errors.include?(:city) %> class="error"<% end %>>City
      <input type="text" name="responses[<%= field.id %>][city]" value="<%= response.details[:city] %>">
    </label>
    <% if response.errors.include?(:city) %>
      <small class="error">
        <ul>
        <% response.errors.full_messages_for(:city).each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </small>
    <% end %>
  </div>
  <div class="small-3 columns">
    <label<% if response.errors.include?(:state) %> class="error"<% end %>>State
      <input type="text" name="responses[<%= field.id %>][state]" value="<%= response.details[:state] %>">
    </label>
    <% if response.errors.include?(:state) %>
      <small class="error">
        <ul>
        <% response.errors.full_messages_for(:state).each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </small>
    <% end %>
  </div>
  <div class="small-3 columns">
    <label<% if response.errors.include?(:zip) %> class="error"<% end %>>ZIP
      <input type="text" name="responses[<%= field.id %>][zip]" value="<%= response.details[:zip] %>">
    </label>
    <% if response.errors.include?(:zip) %>
      <small class="error">
        <ul>
        <% response.errors.full_messages_for(:zip).each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </small>
    <% end %>
  </div>
</div>

backends/rails/app/views/form_responses/_info_field.html.erb
<div class="info-text"><%= md2html(field.details[:text]) %></div>

backends/rails/app/views/form_responses/_long_answer_field.html.erb
<% if field.details[:question] %>
<div class="question"><%= md2html(field.details[:question]) %></div>
<% end %>

<label<% if response.errors.any? %> class="error"<% end %>>
  <%= field.details[:label] %>
  <textarea name="responses[<%= field.id %>][answer]"><%= response.details[:answer] %></textarea>
</label>
<% if response.errors.any? %>
  <small class="error">
    <ul>
    <% response.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </small>
<% end %>

backends/rails/app/views/form_responses/_multiple_choice_field.html.erb
<% if field.details[:question] %>
<div class="question"><%= md2html(field.details[:question]) %></div>
<% end %>

<ul class="choices<% if response.errors.any? %> error<% end %>">
  <% field.details[:choices].each_with_index do |choice, i| %>
  <li class="choice">
      <input type="hidden" name="responses[<%= field.id %>][answers][][label]" value="<%= choice[:label] %>">
      <label><input type="checkbox" name="responses[<%= field.id %>][answers][][selected]" value="1"<% if !response.details[:answers].nil? && response.details[:answers][i][:selected] %> checked<% end %>> <%= choice[:label] %></label>
  </li>
  <% end %>
</ul>
<% if response.errors.any? %>
  <small class="error">
    <ul>
    <% response.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </small>
<% end %>

backends/rails/app/views/form_responses/_short_answer_field.html.erb
<% if field.details[:question] %>
<div class="question"><%= md2html(field.details[:question]) %></div>
<% end %>

<label<% if response.errors.any? %> class="error"<% end %>><%= field.details[:label] %>
  <input type="text" name="responses[<%= field.id %>][answer]" value="<%= response.details[:answer] %>">
</label>
<% if response.errors.any? %>
  <small class="error">
    <ul>
    <% response.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </small>
<% end %>

backends/rails/app/views/form_responses/_single_choice_field.html.erb
<% if field.details[:question] %>
<div class="question"><%= md2html(field.details[:question]) %></div>
<% end %>

<ul class="choices <% if response.errors.any? %> error<% end %>">
  <% field.details[:choices].each do |choice| %>
  <li class="choice"><label><input type="radio" name="responses[<%= field.id %>][answer]" value="<%= choice[:label] %>"<% if response.details[:answer] == choice[:label] %> checked<% end %>> <%= choice[:label] %></label></li>
  <% end %>
</ul>
<% if response.errors.any? %>
  <small class="error">
    <ul>
    <% response.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </small>
<% end %>

backends/rails/app/views/form_responses/done.html.erb
<h1>Form Submitted</h1>
<p>Thank you for filling out the form. It has been submitted successfully.</p>

backends/rails/app/views/form_responses/new.html.erb
<% provide(:title, 'Fill Out Form') %>

<div id="form-new-response">

  <%= form_tag do %>

  <% @form.fields.each do |field| %>
  <div class="row field <%= field.kind %>-field">
    <div class="small-8 columns last">
      <%= render partial: "#{field.kind.underscore}_field", locals: {field: field, response: @field_responses[field.id]} %>
    </div>
  </div>
  <% end %>
  <input type="submit" name="submit" value="Submit" class="button primary small">

  <% end %>

</div>

backends/rails/app/views/form_responses/project_forms.html.erb
<div id="project-forms">
    <h1>Available Forms</h1>

    <% if @forms.empty? %>
    <p class="no-forms">There are no forms available to fill out at this time.</p>
    <% else %>
    <div class="row">
        <div class="large-6 columns last">
            <table id="project-forms-table">
                <thead>
                    <tr>
                        <th>Form</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <% @forms.each do |form| %>
                    <tr>
                        <td><%= link_to form.name.titleize, new_form_response_path(form.project, form.slug) %></td>
                        <td><% if form.description.present? %><%= form.description %><% else %><em>No description provided.</em><% end %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    <% end %>
</div>