backends/rails/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#main'
  get '/subproject', to: 'static_pages#subproject'
  get '/admin', to: 'static_pages#admin'
  get '/admin/*details', to: 'static_pages#admin'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :api, defaults: {format: 'json'} do
    get '/projects', to: 'projects#index'

    get '/forms', to: 'forms#index', as: :forms
    post '/forms', to: 'forms#create'
    get '/forms/:number/versions', to: 'forms#versions', as: :form_versions
    get '/forms/:number/versions/:version', to: 'forms#version', as: :form_version
    put '/forms/:number/versions/:version', to: 'forms#update', as: :form_update
    post '/forms/:number/versions/:version/publish', to: 'forms#publish', as: :form_publish
    post '/forms/:number/versions/:version/unpublish', to: 'forms#unpublish', as: :form_unpublish
    get '/forms/:number/versions/:version/responses', to: 'forms#responses', as: :form_responses
  end

  get '/forms/:project', to: 'form_responses#project_forms', as: :project_forms
  get '/forms/:project/:slug', to: 'form_responses#new', as: :new_form_response
  post '/forms/:project/:slug', to: 'form_responses#create'
  get '/forms/:project/:slug/done', to: 'form_responses#done', as: :form_response_created

end

backends/rails/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def main
    render layout: false
  end

  def subproject
    render layout: 'subproject'
  end

  def admin
    require_staff_or_admin
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
    render layout: false
  end

end

backends/rails/app/views/static_pages/403.html.erb
<%= provide(:title, 'Not Authorized') %>

<h1>Not Authorized</h1>

<p>You are not authorized to access this page.</p>

backends/rails/app/views/static_pages/404.html.erb
<%= provide(:title, 'Page Not Found') %>

<h1>Page Not Found</h1>

<p>The page you were looking for doesn't exist.</p>

backends/rails/app/views/static_pages/500.html.erb
<%= provide(:title, 'Error') %>

<h1>Error</h1>

<p>An internal error occurred on the server. Please try again or contact the website's administrator.</p>

backends/rails/app/views/static_pages/main.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>My Website</title>

    <link rel="stylesheet" type="text/css" href="/assets/css/app.css" media="all" />
    <%= stylesheet_link_tag "css/main" %>
    <%= yield :css %>

    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div id="landing-page">

      <div class="heading">
        <div class="row">
          <div class="large-12 columns">
            <h1>My Website</h1>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="large-12 columns">
          <h2>This Is a Sample Website</h2>
          <p>There isn't much to do just yet, but you can fill out some <%= link_to 'forms', project_forms_path(:main) %>.</p>
          <p>Alternatively, you can check out a <%= link_to 'sub-project', '/subproject' %>.</p>
          <p>And if you're an administrator, you can create, edit, and publish forms of your own in the <%= link_to 'forms admin area', '/admin/forms' %>.</p>
        </div>
      </div>
    </div>
  </body>
</html>

backends/rails/app/views/static_pages/subproject.html.erb
<h1>A Sub-Project</h1>

<p>This is the sub-project area.</p>

<p>There isn't much to do here either, but you can fill out some project-specific <%= link_to 'forms', project_forms_path(:subproject) %>.</p>