backends/rails/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#main'
  get '/subproject', to: 'static_pages#subproject'
  get '/admin', to: 'static_pages#admin'
  get '/admin/*details', to: 'static_pages#admin'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :api, defaults: {format: 'json'} do
    get '/projects', to: 'projects#index'

    get '/forms', to: 'forms#index', as: :forms
    post '/forms', to: 'forms#create'
    get '/forms/:number/versions', to: 'forms#versions', as: :form_versions
    get '/forms/:number/versions/:version', to: 'forms#version', as: :form_version
    put '/forms/:number/versions/:version', to: 'forms#update', as: :form_update
    post '/forms/:number/versions/:version/publish', to: 'forms#publish', as: :form_publish
    post '/forms/:number/versions/:version/unpublish', to: 'forms#unpublish', as: :form_unpublish
    get '/forms/:number/versions/:version/responses', to: 'forms#responses', as: :form_responses
  end

  get '/forms/:project', to: 'form_responses#project_forms', as: :project_forms
  get '/forms/:project/:slug', to: 'form_responses#new', as: :new_form_response
  post '/forms/:project/:slug', to: 'form_responses#create'
  get '/forms/:project/:slug/done', to: 'form_responses#done', as: :form_response_created

end

backends/rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "My Website" %></title>

    <link rel="stylesheet" type="text/css" href="/assets/css/app.css" media="all" />
    <%= stylesheet_link_tag "css/main" %>
    <%= yield :css %>

    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="top-bar contain-to-grid">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1><a href="/">My Website</a></h1>
          </li>
        </ul>

        <section class="top-bar-section">
          <ul class="right">
            <% if logged_in? && (current_user.staff || current_user.admin) %>
            <li class="divider"></li>
            <li><%= link_to "Admin", admin_path %></li>
            <% end %>
            <li class="divider"></li>
            <li>
              <% if logged_in? %>
              <%= link_to "Log Out", logout_path, method: :delete %>
              <% else %>
              <%= link_to "Log In", login_path %>
              <% end %>
            </li>
          </ul>
        </section>
      </nav>
    </div>

    <div class="row">
      <div class="large-12 columns">

        <% flash.reject { |k, v| k == 'done' }.each do |key, value| %>
        <div class="alert-box <%= key %>"><%= value %></div>
        <% end %>

        <%= yield %>

      </div>
    </div>
  </body>
</html>

backends/rails/app/views/layouts/subproject.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Sub-Project" %></title>

    <link rel="stylesheet" type="text/css" href="/assets/css/app.css" media="all" />
    <%= stylesheet_link_tag "css/sub" %>
    <%= yield :css %>

    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="top-bar contain-to-grid">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1><a href="/subproject">My Website | Sub-Project</a></h1>
          </li>
        </ul>

        <section class="top-bar-section">
          <ul class="right">
            <li><%= link_to "My Website Home", root_path %></li>
            <% if logged_in? && (current_user.staff || current_user.admin) %>
            <li class="divider"></li>
            <li><%= link_to "Admin", admin_path %></li>
            <% end %>
            <li class="divider"></li>
            <li>
              <% if logged_in? %>
              <%= link_to "Log Out", logout_path, method: :delete %>
              <% else %>
              <%= link_to "Log In", login_path %>
              <% end %>
            </li>
          </ul>
        </section>
      </nav>
    </div>

    <div class="row">
      <div class="large-12 columns">

        <% flash.reject { |k, v| k == 'done' }.each do |key, value| %>
        <div class="alert-box <%= key %>"><%= value %></div>
        <% end %>

        <%= yield %>

      </div>
    </div>

  </body>
</html>